import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Header from "@/components/header/Header";
import Results from "@/components/results/Results";
import { GetServerSideProps } from "next";
import type { DetailsRandomPageProps } from "@/types/types";
import styles from "@/styles/Home.module.css";
import Details from "@/components/details/Details";

function RandomPage({ data }: { data: DetailsRandomPageProps }) {
  const router = useRouter();
  const [perPage, setPerPage] = useState("4");

  useEffect(() => {
    const perPageValue = localStorage.getItem("perPage") || "4";
    setPerPage(perPageValue);
  }, []);

  function handleSubmit(value: string) {
    if (value === "") return;
    router.push("/photos");
    localStorage.setItem("currentPage", "1");
  }

  function handlePerPageChange(value: string) {
    if (value === perPage) return;
    setPerPage(value);
    localStorage.setItem("currentPage", "1");
  }

  return (
    <>
      <Head>
        <title>Find Images on Unsplash</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        keyWord=""
        perPage={perPage}
        onSubmit={handleSubmit}
        onPerPageChange={handlePerPageChange}
      />
      <main className={styles.main}>
        <Results
          pageType="random"
          totalPagesNumber={1}
          currentPage="1"
          data={data.pageData}
          onPageChange={() => {
            return;
          }}
        />
        <Details pageType="random" details={data.detailsData} />
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<{
  data: DetailsRandomPageProps;
}> = async (context) => {
  console.log(context.query);
  const CLIENT_ID = "cfdYGk4NiOtEue__iSqawbVIwnqHm03dnyVqT6cLXLg";
  const basicUrl = "https://api.unsplash.com/";

  const { per_page, id } = context.query;
  const pageUrl = `${basicUrl}photos/random?count=${per_page}&client_id=${CLIENT_ID}`;
  const detailsUrl = `${basicUrl}photos/${id}/?client_id=${CLIENT_ID}`;

  function getPage() {
    return fetch(pageUrl).then((res) => res.json());
  }
  function getDetails() {
    return fetch(detailsUrl).then((res) => res.json());
  }

  const [pageData, detailsData] = await Promise.all([getPage(), getDetails()]);

  return { props: { data: { pageData: pageData, detailsData: detailsData } } };
};

export default RandomPage;
