import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Header from "@/components/header/Header";
import Results from "@/components/results/Results";
import { GetServerSideProps } from "next";
import type { DataItem } from "@/types/types";
import styles from "@/styles/Home.module.css";

function RandomPage({ data }: { data: DataItem[] }) {
  const router = useRouter();
  const [perPage, setPerPage] = useState("4");

  useEffect(() => {
    const perPageValue = localStorage.getItem("perPage") || "4";
    setPerPage(perPageValue);
  }, []);

  useEffect(() => {
    router.push(`random/?per_page=${perPage}`, undefined, {
      shallow: false,
    });
  }, [perPage]);

  function handleSubmit(value: string) {
    if (value === "") return;
    router.push("/photos");
    localStorage.setItem("currentPage", "1");
  }

  function handlePerPageChange(value: string) {
    if (value === perPage) return;
    setPerPage(value);
    localStorage.setItem("currentPage", "1");
  }

  return (
    <>
      <Head>
        <title>Find Images on Unsplash</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        keyWord=""
        perPage={perPage}
        onSubmit={handleSubmit}
        onPerPageChange={handlePerPageChange}
      />
      <main className={styles.main}>
        <Results
          pageType="random"
          totalPagesNumber={1}
          currentPage="1"
          data={data}
          onPageChange={() => {
            return;
          }}
        />
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps<{
  data: DataItem[];
}> = async (context) => {
  console.log(context.query);
  const CLIENT_ID = "cfdYGk4NiOtEue__iSqawbVIwnqHm03dnyVqT6cLXLg";
  const basicUrl = "https://api.unsplash.com/";
  const { per_page } = context.query;
  const res = await fetch(
    `${basicUrl}photos/random?count=${per_page}&client_id=${CLIENT_ID}`,
  );
  const data = await res.json();
  return { props: { data } };
};

export default RandomPage;
