import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Header from "@/components/header/Header";
import styles from "@/styles/Home.module.css";

export default function RandomPage() {
  const [perPage, setPerPage] = useState("4");
  const router = useRouter();

  useEffect(() => {
    const perPageValue = localStorage.getItem("perPage") || "4";
    setPerPage(perPageValue);
  }, []);

  useEffect(() => {
    router.push(`random/?per_page=${perPage}`, undefined, {
      shallow: true,
    });
  }, [perPage, router]);

  function handleSubmit(value: string) {
    if (value === "") return;
    localStorage.setItem("keyWord", value);
    router.push("/photos");
    localStorage.setItem("currentPage", "1");
  }

  function handlePerPageChange(value: string) {
    if (value === perPage) return;
    localStorage.setItem("perPage", value);
    setPerPage(value);
    localStorage.setItem("currentPage", "1");
  }

  return (
    <>
      <Head>
        <title>Find Images on Unsplash</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p style={{ color: "red", padding: "10px 0" }}>
        <b>Module05 is not finished. Please check later!</b>
      </p>
      <Header
        keyWord=""
        perPage={perPage}
        onSubmit={handleSubmit}
        onPerPageChange={handlePerPageChange}
      />
      <main className={styles.main}></main>
    </>
  );
}
