import { useEffect } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  const router = useRouter();

  const move = (search: string) => {
    if (search) {
      router.push("/photos");
    } else {
      router.push("/random");
    }
  };

  useEffect(() => {
    const keyWord = localStorage.getItem("keyWord") || "";
    move(keyWord);
  }, []);

  return (
    <>
      <Head>
        <title>Find Images on Unsplash</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>Thinking...</p>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const data = null;
  return { props: { data } };
};
