import Head from "next/head";
import RootLayout from "@/layouts/RootLayout";
import styles from "./404.module.css";

export default function Page404() {
  return (
    <>
      <Head>
        <title>Find Images on Unsplash</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.page_title}>
          <span>FIND IMAGES ON</span>
        </div>
        <h2 className={styles.h2}>PAGE NOT FOUND!</h2>
      </header>
    </>
  );
}

Page404.getLayout = (page) => {
  return <RootLayout>{page}</RootLayout>;
};
